revendor bottledaemon
Cram tests are broken:

Traceback (most recent call last):
  File "src/cmdlinetest/afp_mock.py", line 28, in <module>
    daemon_run(host='localhost', port=5555)
  File "/data/home/vhaenel/virtualenv/gnome-keyring/local/lib/python2.7/site-packages/bottledaemon/bottledaemon.py", line 64, in daemon_run
    with context:
  File "/data/home/vhaenel/virtualenv/gnome-keyring/local/lib/python2.7/site-packages/daemon/daemon.py", line 394, in __enter__
    self.open()
  File "/data/home/vhaenel/virtualenv/gnome-keyring/local/lib/python2.7/site-packages/daemon/daemon.py", line 370, in open
    change_process_owner(self.uid, self.gid, self.initgroups)
  File "/data/home/vhaenel/virtualenv/gnome-keyring/local/lib/python2.7/site-packages/daemon/daemon.py", line 642, in change_process_owner
    raise error
daemon.daemon.DaemonOSEnvironmentError: Unable to change process owner ([Errno 1] Operation not permitted)

Since python-daemon 2.1 initgroups requires root priviledges. Bottledaemon
doesn't support passing the initgroups=False to the uderlying python-daemon, so
we need to vendor it and modify this manually.